site:
  title: Documentation
  url: http:localhost:5000
  start_page: sonar:ROOT:sonar-assignment.adoc
  robots: disallow
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  attributes:
    # Download images from kroki at build time (does not work for inline images)
    kroki-fetch-diagram: true
    # Inlude next and previous links on each page
    page-pagination: true@
    idprefix: ''
    # Separate anchor link names by dashes
    idseparator: '-'
  extensions:
    - asciidoctor-kroki