= Importing GitHub Repositories


SonarQube's integration with GitHub Enterprise and GitHub.com allows you to maintain code quality and security in your GitHub repositories.

With this integration, you can import your GitHub repositories. Importing your GitHub repositories into SonarQube allows you to easily set up SonarQube projects.

== Prerequisites

To integrate with GitHub Enterprise, you must be running GitHub Enterprise version 2.15+.

???

== Importing your GitHub repositories into SonarQube

You need to use a GitHub App to connect SonarQube and GitHub so you can import your GitHub repositories into SonarQube.

In this section, you'll complete the following steps to connect SonarQube and GitHub with a GitHub App:

. Create your GitHub App.
. Install your GitHub App in your organization.
. Update your SonarQube global settings with your GitHub App information.

=== Step 1: Creating your GitHub App

See GitHub's documentation on http://???[creating a GitHub App] for general information on creating a GitHub App.

=== Step 2: Installing your GitHub App in your organization

Next, you need to install your GitHub App in your organizations. See GitHub's documentation on http:???[installing GitHub Apps] for more information.

=== Step 3: Updating your SonarQube global settings with your GitHub App information

After you've created and installed your GitHub App, update your global SonarQube settings to finish integration and allow for the import of GitHub projects.

Navigate to Administration > Configuration > General Settings > ALM Integrations and specify the following settings:

* GitHub API URL – For example, https://github.company.com/api/v3 for GitHub Enterprise or https://api.github.com/ for GitHub.com.
* GitHub App Name –
* GitHub Application ID – The App ID is found on your GitHub App's page on GitHub at Settings > Developer Settings > GitHub Apps.
* Private Key – Your GitHub App's private key. You can generate a .pem file from your GitHub App's page under Private keys. Copy and paste the contents of the file here.

== Authenticating with GitHub //aligning the heading text to be task oriented

To allow users to log in to SonarQube with their GitHub credentials, you can use the same GitHub App that you use to import your GitHub projects. For information on creating this GitHub app, see the documentation on Importing GitHub Repositories.

You also need to update your global SonarQube settings. To update these settings:

Navigate to Administration > Configuration > General Settings > GitHub and update the following:

1. Enabled – Set the switch to true.
2. Client ID – the Client ID is found below the GitHub App ID on your GitHub App's page
3. Client Secret – The Client secret is found below the Client ID on your GitHub App's page.

Now, users can connect their GitHub accounts from the login page using the new "Log in with GitHub" button.